# coding=utf-8
cities = {
    'Москва': 'moskva',
    'Санкт-Петербург': 'sankt-peterburg',
    'Астрахань': 'astrahan',
    'Барнаул': 'barnaul',
    'Волгоград': 'volgograd',
    'Воронеж': 'voronezh',
    'Екатеринбург': 'ekaterinburg',
    'Ижевск': 'izhevsk',
    'Иркутск': 'irkutsk',
    'Казань': 'kazan',
    'Калининград': 'kaliningrad',
    'Краснодар': 'krasnodar',
    'Красноярск': 'krasnoyarsk',
    'Набережные Челны': 'naberezhnye_chelny',
    'Нижний Новгород': 'nizhniy_novgorod',
    'Новосибирск': 'novosibirsk',
    'Омск': 'omsk',
    'Оренбург': 'orenburg',
    'Пермь':'perm',
    'Растов-на-Дону': 'rostov-na-donu',
    'Самара': 'samara',
    'Саратов': 'saratov',
    'Ставрополь': 'stavropol',
    'Тольятти': 'tolyatti',
    'Тула': 'tula',
    'Тюмень': 'tyumen',
    'Уьляновск': 'ulyanovsk',
    'Уфа': 'ufa',
    'Челябинск': 'chelyabinsk',
    'Ярославль': 'yaroslavl',
    'москва': 'moskva',
    'санкт-Петербург': 'sankt-peterburg',
    'астрахань': 'astrahan',
    'барнаул': 'barnaul',
    'волгоград': 'volgograd',
    'воронеж': 'voronezh',
    'екатеринбург': 'ekaterinburg',
    'ижевск': 'izhevsk',
    'иркутск': 'irkutsk',
    'казань': 'kazan',
    'калининград': 'kaliningrad',
    'краснодар': 'krasnodar',
    'красноярск': 'krasnoyarsk',
    'набережные Челны': 'naberezhnye_chelny',
    'нижний Новгород': 'nizhniy_novgorod',
    'новосибирск': 'novosibirsk',
    'омск': 'omsk',
    'оренбург': 'orenburg',
    'пермь':'perm',
    'растов-на-Дону': 'rostov-na-donu',
    'самара': 'samara',
    'саратов': 'saratov',
    'ставрополь': 'stavropol',
    'тольятти': 'tolyatti',
    'тула': 'tula',
    'тюмень': 'tyumen',
    'уьляновск': 'ulyanovsk',
    'уфа': 'ufa',
    'челябинск': 'chelyabinsk',
    'ярославль': 'yaroslavl',
    'санкт-петербург': 'sankt-peterburg',
    'спб': 'sankt-peterburg',
    'СПБ': 'sankt-peterburg',
    'НН': 'nizhniy_novgorod'
          }